services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - caddy
    command: bash -c 'sleep 3 && npm start'
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile

volumes:
  pgdata:
