services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    command: bash -c 'npm run dev'
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
  # Dummy DB service to override unused postgres db in Dev env.
  db:
    image: alpine:latest
    command: "true"
    restart: no
    entrypoint: "true"
