name: push

on:
  push:
    branches:
      - 'main'

env:
  CI: true
  APP_IMAGE_NAME: azeos1101/devops-for-programmers-project-74

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Prepear env
        run: cd ./app && make prepare-env
      -
        name: Run tests
        run: make test
  docker:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest
